export namespace Palette {
  export const themePrimary = 'var(--themePrimary, #0078d4)'
  export const themeLighterAlt = 'var(--themeLighterAlt, #eff6fc)'
  export const themeLighter = 'var(--themeLighter, #deecf9)'
  export const themeLight = 'var(--themeLight, #c7e0f4)'
  export const themeTertiary = 'var(--themeTertiary, #71afe5)'
  export const themeSecondary = 'var(--themeSecondary, #2b88d8)'
  export const themeDarkAlt = 'var(--themeDarkAlt, #106ebe)'
  export const themeDark = 'var(--themeDark, #005a9e)'
  export const themeDarker = 'var(--themeDarker, #004578)'
  export const neutralLighterAlt = 'var(--neutralLighterAlt, #faf9f8)'
  export const neutralLighter = 'var(--neutralLighter, #f3f2f1)'
  export const neutralLight = 'var(--neutralLight, #edebe9)'
  export const neutralQuaternaryAlt = 'var(--neutralQuaternaryAlt, #e1dfdd)'
  export const neutralQuaternary = 'var(--neutralQuaternary, #d0d0d0)'
  export const neutralTertiaryAlt = 'var(--neutralTertiaryAlt, #c8c6c4)'
  export const neutralTertiary = 'var(--neutralTertiary, #a19f9d)'
  export const neutralSecondaryAlt = 'var(--neutralSecondaryAlt, #8a8886)'
  export const neutralSecondary = 'var(--neutralSecondary, #605e5c)'
  export const neutralPrimaryAlt = 'var(--neutralPrimaryAlt, #3b3a39)'
  export const neutralPrimary = 'var(--neutralPrimary, #323130)'
  export const neutralDark = 'var(--neutralDark, #201f1e)'
  export const black = 'var(--black, #000000)'
  export const white = 'var(--white, #ffffff)'
}
