import type { IPalette } from '../types/index'

// When adding or removing a color, make sure you keep this consistent with IColorClassNames
// by adding the color variants.
export const DefaultPalette: IPalette = {
  themePrimary: 'var(--themePrimary, #0078d4)',
  themeLighterAlt: 'var(--themeLighterAlt, #eff6fc)',
  themeLighter: 'var(--themeLighter, #deecf9)',
  themeLight: 'var(--themeLight, #c7e0f4)',
  themeTertiary: 'var(--themeTertiary, #71afe5)',
  themeSecondary: 'var(--themeSecondary, #2b88d8)',
  themeDarkAlt: 'var(--themeDarkAlt, #106ebe)',
  themeDark: 'var(--themeDark, #005a9e)',
  themeDarker: 'var(--themeDarker, #004578)',
  neutralLighterAlt: 'var(--neutralLighterAlt, #faf9f8)',
  neutralLighter: 'var(--neutralLighter, #f3f2f1)',
  neutralLight: 'var(--neutralLight, #edebe9)',
  neutralQuaternaryAlt: 'var(--neutralQuaternaryAlt, #e1dfdd)',
  neutralQuaternary: 'var(--neutralQuaternary, #d0d0d0)',
  neutralTertiaryAlt: 'var(--neutralTertiaryAlt, #c8c6c4)',
  neutralTertiary: 'var(--neutralTertiary, #a19f9d)',
  neutralSecondaryAlt: 'var(--neutralSecondaryAlt, #8a8886)',
  neutralSecondary: 'var(--neutralSecondary, #605e5c)',
  neutralPrimaryAlt: 'var(--neutralPrimaryAlt, #3b3a39)',
  neutralPrimary: 'var(--neutralPrimary, #323130)',
  neutralDark: 'var(--neutralDark, #201f1e)',
  black: 'var(--black, #000000)',
  white: 'var(--white, #ffffff)',

  blackTranslucent40: 'rgba(0,0,0,.4)',
  accent: '#0078d4',
  whiteTranslucent40: 'rgba(255,255,255,.4)',
  yellowDark: '#d29200',
  yellow: '#ffb900',
  yellowLight: '#fff100',
  orange: '#d83b01',
  orangeLight: '#ea4300',
  orangeLighter: '#ff8c00',
  redDark: '#a4262c',
  red: '#e81123',
  magentaDark: '#5c005c',
  magenta: '#b4009e',
  magentaLight: '#e3008c',
  purpleDark: '#32145a',
  purple: '#5c2d91',
  purpleLight: '#b4a0ff',
  blueDark: '#002050',
  blueMid: '#00188f',
  blue: '#0078d4',
  blueLight: '#00bcf2',
  tealDark: '#004b50',
  teal: '#008272',
  tealLight: '#00b294',
  greenDark: '#004b1c',
  green: '#107c10',
  greenLight: '#bad80a',
}
