import { getCssVarName } from '../getCssVarName'
import type { IPalette } from '../types/index'

// When adding or removing a color, make sure you keep this consistent with IColorClassNames
// by adding the colorgetCssVarName( ts'.
export const DefaultPalette: IPalette = {
  themePrimary: getCssVarName('themePrimary', '#0078d4'),
  themeLighterAlt: getCssVarName('themeLighterAlt', '#eff6fc'),
  themeLighter: getCssVarName('themeLighter', '#deecf9'),
  themeLight: getCssVarName('themeLight', '#c7e0f4'),
  themeTertiary: getCssVarName('themeTertiary', '#71afe5'),
  themeSecondary: getCssVarName('themeSecondary', '#2b88d8'),
  themeDarkAlt: getCssVarName('themeDarkAlt', '#106ebe'),
  themeDark: getCssVarName('themeDark', '#005a9e'),
  themeDarker: getCssVarName('themeDarker', '#004578'),
  neutralLighterAlt: getCssVarName('neutralLighterAlt', '#faf9f8'),
  neutralLighter: getCssVarName('neutralLighter', '#f3f2f1'),
  neutralLight: getCssVarName('neutralLight', '#edebe9'),
  neutralQuaternaryAlt: getCssVarName('neutralQuaternaryAlt', '#e1dfdd'),
  neutralQuaternary: getCssVarName('neutralQuaternary', '#d0d0d0'),
  neutralTertiaryAlt: getCssVarName('neutralTertiaryAlt', '#c8c6c4'),
  neutralTertiary: getCssVarName('neutralTertiary', '#a19f9d'),
  neutralSecondaryAlt: getCssVarName('neutralSecondaryAlt', '#8a8886'),
  neutralSecondary: getCssVarName('neutralSecondary', '#605e5c'),
  neutralPrimaryAlt: getCssVarName('neutralPrimaryAlt', '#3b3a39'),
  neutralPrimary: getCssVarName('neutralPrimary', '#323130'),
  neutralDark: getCssVarName('neutralDark', '#201f1e'),
  black: getCssVarName('black', '#000000'),
  white: getCssVarName('white', '#ffffff'),

  blackTranslucent40: 'rgba(0,0,0,.4)',
  accent: '#0078d4',
  whiteTranslucent40: 'rgba(255,255,255,.4)',
  yellowDark: '#d29200',
  yellow: '#ffb900',
  yellowLight: '#fff100',
  orange: '#d83b01',
  orangeLight: '#ea4300',
  orangeLighter: '#ff8c00',
  redDark: '#a4262c',
  red: '#e81123',
  magentaDark: '#5c005c',
  magenta: '#b4009e',
  magentaLight: '#e3008c',
  purpleDark: '#32145a',
  purple: '#5c2d91',
  purpleLight: '#b4a0ff',
  blueDark: '#002050',
  blueMid: '#00188f',
  blue: '#0078d4',
  blueLight: '#00bcf2',
  tealDark: '#004b50',
  teal: '#008272',
  tealLight: '#00b294',
  greenDark: '#004b1c',
  green: '#107c10',
  greenLight: '#bad80a',
}
