export namespace FontSizes {
  export const mini: string = '10px'
  export const xSmall: string = '10px'
  export const small: string = '12px'
  export const smallPlus: string = '12px'
  export const medium: string = '14px'
  export const mediumPlus: string = '16px'
  export const icon: string = '16px'
  export const large: string = '18px'
  export const xLarge: string = '20px'
  export const xLargePlus: string = '24px'
  export const xxLarge: string = '28px'
  export const xxLargePlus: string = '32px'
  export const superLarge: string = '42px'
  export const mega: string = '68px'
}
