import { getCssVarName } from './getCssVarName'

export namespace Palette {
  export const themePrimary = getCssVarName('themePrimary', '#0078d4')
  export const themeLighterAlt = getCssVarName('themeLighterAlt', '#eff6fc')
  export const themeLighter = getCssVarName('themeLighter', '#deecf9')
  export const themeLight = getCssVarName('themeLight', '#c7e0f4')
  export const themeTertiary = getCssVarName('themeTertiary', '#71afe5')
  export const themeSecondary = getCssVarName('themeSecondary', '#2b88d8')
  export const themeDarkAlt = getCssVarName('themeDarkAlt', '#106ebe')
  export const themeDark = getCssVarName('themeDark', '#005a9e')
  export const themeDarker = getCssVarName('themeDarker', '#004578')
  export const neutralLighterAlt = getCssVarName('neutralLighterAlt', '#faf9f8')
  export const neutralLighter = getCssVarName('neutralLighter', '#f3f2f1')
  export const neutralLight = getCssVarName('neutralLight', '#edebe9')
  export const neutralQuaternaryAlt = getCssVarName('neutralQuaternaryAlt', '#e1dfdd')
  export const neutralQuaternary = getCssVarName('neutralQuaternary', '#d0d0d0')
  export const neutralTertiaryAlt = getCssVarName('neutralTertiaryAlt', '#c8c6c4')
  export const neutralTertiary = getCssVarName('neutralTertiary', '#a19f9d')
  export const neutralSecondaryAlt = getCssVarName('neutralSecondaryAlt', '#8a8886')
  export const neutralSecondary = getCssVarName('neutralSecondary', '#605e5c')
  export const neutralPrimaryAlt = getCssVarName('neutralPrimaryAlt', '#3b3a39')
  export const neutralPrimary = getCssVarName('neutralPrimary', '#323130')
  export const neutralDark = getCssVarName('neutralDark', '#201f1e')
  export const black = getCssVarName('black', '#000000')
  export const white = getCssVarName('white', '#ffffff')
}
