import { getCssVarName } from './getCssVarName'
import { Palette } from './Palette'

export namespace SemanticColors {
  export const bodyBackground = Palette.white
  export const bodyFrameBackground = Palette.white
  export const accentButtonText = Palette.white
  export const buttonBackground = Palette.white
  export const primaryButtonText = Palette.white
  export const primaryButtonTextHovered = Palette.white
  export const primaryButtonTextPressed = Palette.white
  export const inputBackground = Palette.white
  export const inputForegroundChecked = Palette.white
  export const listBackground = Palette.white
  export const menuBackground = Palette.white
  export const cardStandoutBackground = Palette.white
  export const bodyTextChecked = Palette.black
  export const buttonTextCheckedHovered = Palette.black
  export const link = Palette.themePrimary
  export const primaryButtonBackground = Palette.themePrimary
  export const inputBackgroundChecked = Palette.themePrimary
  export const inputIcon = Palette.themePrimary
  export const inputFocusBorderAlt = Palette.themePrimary
  export const menuIcon = Palette.themePrimary
  export const menuHeader = Palette.themePrimary
  export const accentButtonBackground = Palette.themePrimary
  export const primaryButtonBackgroundPressed = Palette.themeDark
  export const inputBackgroundCheckedHovered = Palette.themeDark
  export const inputIconHovered = Palette.themeDark
  export const linkHovered = Palette.themeDarker
  export const primaryButtonBackgroundHovered = Palette.themeDarkAlt
  export const inputPlaceholderBackgroundChecked = Palette.themeLighter
  export const bodyBackgroundChecked = Palette.neutralLight
  export const bodyFrameDivider = Palette.neutralLight
  export const bodyDivider = Palette.neutralLight
  export const variantBorder = Palette.neutralLight
  export const buttonBackgroundCheckedHovered = Palette.neutralLight
  export const buttonBackgroundPressed = Palette.neutralLight
  export const listItemBackgroundChecked = Palette.neutralLight
  export const listHeaderBackgroundPressed = Palette.neutralLight
  export const menuItemBackgroundPressed = Palette.neutralLight
  export const menuItemBackgroundChecked = Palette.neutralLight
  export const bodyBackgroundHovered = Palette.neutralLighter
  export const buttonBackgroundHovered = Palette.neutralLighter
  export const buttonBackgroundDisabled = Palette.neutralLighter
  export const buttonBorderDisabled = Palette.neutralLighter
  export const primaryButtonBackgroundDisabled = Palette.neutralLighter
  export const disabledBackground = Palette.neutralLighter
  export const listItemBackgroundHovered = Palette.neutralLighter
  export const listHeaderBackgroundHovered = Palette.neutralLighter
  export const menuItemBackgroundHovered = Palette.neutralLighter
  export const primaryButtonTextDisabled = Palette.neutralQuaternary
  export const disabledSubtext = Palette.neutralQuaternary
  export const listItemBackgroundCheckedHovered = Palette.neutralQuaternaryAlt
  export const disabledBodyText = Palette.neutralTertiary
  export const variantBorderHovered = Palette.neutralTertiary
  export const buttonTextDisabled = Palette.neutralTertiary
  export const inputIconDisabled = Palette.neutralTertiary
  export const disabledText = Palette.neutralTertiary
  export const bodyText = Palette.neutralPrimary
  export const actionLink = Palette.neutralPrimary
  export const buttonText = Palette.neutralPrimary
  export const inputBorderHovered = Palette.neutralPrimary
  export const inputText = Palette.neutralPrimary
  export const listText = Palette.neutralPrimary
  export const menuItemText = Palette.neutralPrimary
  export const bodyStandoutBackground = Palette.neutralLighterAlt
  export const defaultStateBackground = Palette.neutralLighterAlt
  export const actionLinkHovered = Palette.neutralDark
  export const buttonTextHovered = Palette.neutralDark
  export const buttonTextChecked = Palette.neutralDark
  export const buttonTextPressed = Palette.neutralDark
  export const inputTextHovered = Palette.neutralDark
  export const menuItemTextHovered = Palette.neutralDark
  export const bodySubtext = Palette.neutralSecondary
  export const focusBorder = Palette.neutralSecondary
  export const inputBorder = Palette.neutralSecondary
  export const smallInputBorder = Palette.neutralSecondary
  export const inputPlaceholderText = Palette.neutralSecondary
  export const buttonBorder = Palette.neutralSecondaryAlt
  export const disabledBodySubtext = Palette.neutralTertiaryAlt
  export const disabledBorder = Palette.neutralTertiaryAlt
  export const buttonBackgroundChecked = Palette.neutralTertiaryAlt
  export const menuDivider = Palette.neutralTertiaryAlt
  export const cardShadowHovered = `0 0 1px ${Palette.neutralTertiary}`
  export const primaryButtonBorder = getCssVarName('primaryButtonBorder', ' transparent')
  export const errorText = getCssVarName('errorText', '#a4262c')
  export const messageText = getCssVarName('messageText', '#323130')
  export const messageLink = getCssVarName('messageLink', '#005A9E')
  export const messageLinkHovered = getCssVarName('messageLinkHovered', '#004578')
  export const infoIcon = getCssVarName('infoIcon', '#605e5c')
  export const errorIcon = getCssVarName('errorIcon', '#A80000')
  export const blockingIcon = getCssVarName('blockingIcon', '#FDE7E9')
  export const warningIcon = getCssVarName('warningIcon', '#797775')
  export const severeWarningIcon = getCssVarName('severeWarningIcon', '#D83B01')
  export const successIcon = getCssVarName('successIcon', '#107C10')
  export const infoBackground = getCssVarName('infoBackground', '#f3f2f1')
  export const errorBackground = getCssVarName('errorBackground', '#FDE7E9')
  export const blockingBackground = getCssVarName('blockingBackground', '#FDE7E9')
  export const warningBackground = getCssVarName('warningBackground', '#FFF4CE')
  export const severeWarningBackground = getCssVarName('severeWarningBackground', '#FED9CC')
  export const successBackground = getCssVarName('successBackground', '#DFF6DD')
  export const warningHighlight = getCssVarName('warningHighlight', '#ffb900')
  export const successText = getCssVarName('successText', '#107C10')
  export const listTextColor = Palette.neutralPrimary
  export const warningText = getCssVarName('warningText', '#323130')
}
